export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE=~/.history
setopt AUTOMENU AUTO_CD AUTO_REMOVE_SLASH AUTO_RESUME EXTENDED_GLOB
setopt EXTENDED_HISTORY HIST_IGNORE_DUPS LIST_TYPES MARKDIRS
setopt MENU_COMPLETE PUSHD_IGNORE_DUPS AUTO_PUSHD SHARE_HISTORY INC_APPEND_HISTORY APPEND_HISTORY

